dist: bionic
sudo: false
os: linux
language: java
script: make
env:
  global:
    secure: xLKekvF1JtdzW1u0rb1sWwwlKb/Qm7w6CyT4k45JflJ0aLOCxRK5Yrb5Yvt0lPT9ePPpaafySeslijsIRX2izJL8EHkf/CwjPt6J9JUc3X74LgDDz7pBKYB9DOJ0p4ANTLCEReDResX6WLqSgmeiJubKfy7hwka7NlxZcej7ogleW2zTxYaRRfzkkfapAA0pW+xNS0IP5LprSxdPEP2o98r2/XEkEn0XUB1f2q+x0T/27jyVHxsXyVpwioEigATfcxtcjj6s+sgwokJ+3mfWOY7QUbm+DTA9X6nMf8cZw/0PWa1Bw0nPLHqtH3co3e7o1kTJCxjNAop59hh5uSdJgVTsrm1mXYfMSfTF7Z4pweGqkodHTbhyit7rRx8LeXBRNrOHs9iZvK0nCA+xSMM9ejXwHAlr2Tu3O4s6m7eSz/nK9hW2O/ezGdrj2bnQTLh9qwoatElLth+tW5fcETKkrol0KM5iKYnudEL5psBTx8s8y0t/j1khVIgLLyjzmVNMKXRkHxFB3aTAI/dOhq1OU/PCazf7lgTi0YSdu50qWlhbADyNYo4mBKG3KOcyPv9AtN03WBsFpRO7wj9jQNYzz8EzD65wvXPpBKDZuxpOWzzglO6SFl1wDPl94xkMGbmRD7m7qEOCWYqRUItk0OEK99y4ELSctlp883j9XqwPw6I=
